AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: The GraphQL release API, developed by @wolfeidau

Parameters:
  AppName:
    Type: String
    Description: The application name
  Branch:
    Type: String
    Description: Git branch
    Default: "master"
  Stage:
    Type: String
    Description: Deployment stage
    Default: 'dev'
  RawEventLogging:
    Type: String
    Default: "false"
  OpenIDConnectIssuer:
    Description: The OIDC Issuer which is typically a dev-xxxxxx.oktapreview.com for an Okta dev account.
    Type: String
  OpenIDConnectClientId:
    Description: The OIDC Client Identifier which is an alphanumeric value for an Okta SPA application (implicit flow).
    Type: String

Globals:
  Function:
    Runtime: go1.x
    Timeout: 30
    MemorySize: 1024
    Tracing: Active
    Environment:
      Variables:
        APP_NAME: !Ref AppName
        BRANCH: !Ref Branch
        STAGE: !Ref Stage
        RAW_EVENT_LOGGING: !Ref RawEventLogging

Resources:

  ReleaseTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiry
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ReleasesGraphQLAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: '../../dist/handler.zip'
      Handler: lambda-api
      Environment:
        Variables:
          RELEASE_TABLE: !Ref ReleaseTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !GetAtt ReleaseTable.Arn

  ReleasesAppSyncLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/appsync/apis/${ReleasesGraphQLApi.ApiId}"

  AppSyncServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs

  AppSyncLambdaInvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "Releases-${Stage}-${Branch}-AppSyncLambdaInvokePolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:*
            Resource:
              - "*"
      Roles:
        - !Ref AppSyncServiceRole

  ReleasesGraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub "ReleasesGraphQLApi-${Stage}-${Branch}"
      AuthenticationType: OPENID_CONNECT
      OpenIDConnectConfig:
        ClientId: !Ref OpenIDConnectClientId
        Issuer: !Ref OpenIDConnectIssuer
      XrayEnabled: true
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncServiceRole.Arn
        FieldLogLevel: "ERROR"

  AppSyncActivitySchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt ReleasesGraphQLApi.ApiId
      DefinitionS3Location: ../../graphql/schema.graphql

  ReleasesGraphQLAPILambdaDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt ReleasesGraphQLApi.ApiId
      Name: "ReleasesGraphQLAPILambdaDataSource"
      Description: "GraphQL API Lambda data source"
      Type: "AWS_LAMBDA"
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt ReleasesGraphQLAPIFunction.Arn

  ReleaseCreateQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt ReleasesGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: releaseCreate
      DataSourceName: !GetAtt "ReleasesGraphQLAPILambdaDataSource.Name"
      RequestMappingTemplate: |
        {
            "version": "2018-05-29",
            "operation": "Invoke",
            "payload": {
                "typeName": "$ctx.info.parentTypeName",
                "field": "$ctx.info.fieldName",
                "identity": $utils.toJson($ctx.identity),
                "arguments":  $utils.toJson($context.arguments)
            }
        }
      ResponseMappingTemplate: |
        #if($ctx.error)
          $util.error($context.error.message, $context.error.type)
        #end
        $util.toJson($context.result)

  ReleaseQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt ReleasesGraphQLApi.ApiId
      TypeName: Query
      FieldName: release
      DataSourceName: !GetAtt "ReleasesGraphQLAPILambdaDataSource.Name"
      RequestMappingTemplate: |
        {
            "version": "2018-05-29",
            "operation": "Invoke",
            "payload": {
                "typeName": "$ctx.info.parentTypeName",
                "field": "$ctx.info.fieldName",
                "identity": $utils.toJson($ctx.identity),
                "arguments":  $utils.toJson($context.arguments)
            }
        }
      ResponseMappingTemplate: |
        #if($ctx.error)
          $util.error($context.error.message, $context.error.type)
        #end
        $util.toJson($context.result)

  ReleaseListQueryResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt ReleasesGraphQLApi.ApiId
      TypeName: Query
      FieldName: releaseList
      DataSourceName: !GetAtt "ReleasesGraphQLAPILambdaDataSource.Name"
      RequestMappingTemplate: |
        {
            "version": "2018-05-29",
            "operation": "Invoke",
            "payload": {
                "typeName": "$ctx.info.parentTypeName",
                "field": "$ctx.info.fieldName",
                "identity": $utils.toJson($ctx.identity),
                "arguments":  $utils.toJson($context.arguments)
            }
        }
      ResponseMappingTemplate: |
        #if($ctx.error)
          $util.error($context.error.message, $context.error.type)
        #end
        $util.toJson($context.result)

  ApiAvailability:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub 'AppSync ReleasesGraphQLApi-${Stage}-${Branch} availability is lower than 99%'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ReleasesGraphQLAPIId
          Value: !Sub "${ReleasesGraphQLApi.ApiId}"
      EvaluationPeriods: 5
      MetricName: 5XXErrors
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Average
      Threshold: 0.01
      TreatMissingData: notBreaching

  AppSyncDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardName: !Sub "Releases-Dashboard-${Stage}-${Branch}-${AWS::Region}"
      DashboardBody: !Sub >
        {
            "widgets": [
                {
                    "type": "text",
                    "x": 0,
                    "y": 0,
                    "width": 24,
                    "height": 1,
                    "properties": {
                        "markdown": "\n# AppSync ${AppName}\n"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 1,
                    "width": 24,
                    "height": 9,
                    "properties": {
                        "metrics": [
                            [ { "expression": "(m2/m1)*100", "label": "percentage", "id": "e1", "yAxis": "right" } ],
                            [ "AWS/AppSync", "5XXError", "ReleasesGraphQLAPIId", "${ReleasesGraphQLApi.ApiId}", { "label": "5xx errors", "id": "m2" } ],
                            [ "...", { "stat": "SampleCount", "label": "total requests", "id": "m1" } ]
                        ],
                        "region": "${AWS::Region}",
                        "title": "AppSync - 500 Errors vs Total Requests and SLA %",
                        "stat": "Sum",
                        "yAxis": {
                            "left": {
                                "label": "Count",
                                "showUnits": false
                            },
                            "right": {
                                "min": 0,
                                "max": 10,
                                "label": "Percentage Errors"
                            }
                        },
                        "view": "timeSeries",
                        "stacked": false,
                        "annotations": {
                            "horizontal": [
                                {
                                    "label": "% Availability SLA Threshold",
                                    "value": 1,
                                    "yAxis": "right"
                                }
                            ]
                        },
                        "period": 3600
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 10,
                    "width": 24,
                    "height": 9,
                    "properties": {
                        "metrics": [
                            [ "AWS/AppSync", "Latency", "ReleasesGraphQLAPIId", "${ReleasesGraphQLApi.ApiId}", { "stat": "p90", "period": 60 } ]
                        ],
                        "region": "${AWS::Region}",
                        "title": "AppSync - Latency P90",
                        "stat": "Sum",
                        "yAxis": {
                            "left": {
                                "label": "Count",
                                "showUnits": false
                            }
                        },
                        "view": "timeSeries",
                        "stacked": false,
                        "period": 3600
                    }
                }
            ]
        }

  AppSyncDashboardName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/config/${AppName}/${Stage}/${Branch}/cloudwatch/DashboardName"
      Type: "String"
      Value: !Ref AppSyncDashboard
      Description: "AppSync Dashboard name"

  AppSyncURLParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/config/${AppName}/${Stage}/${Branch}/appsync_url"
      Type: String
      Value: !GetAtt ReleasesGraphQLApi.GraphQLUrl

Outputs:
  AppSyncDashboardName:
    Value: !Ref AppSyncDashboard
  AppSyncURL:
    Value: !GetAtt ReleasesGraphQLApi.GraphQLUrl
