// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateReleaseInput struct {
	GitHash     string `json:"gitHash"`
	Author      string `json:"author"`
	Approver    string `json:"approver"`
	RepoURL     string `json:"repoURL"`
	ArtifactURL string `json:"artifactURL"`
}

type Release struct {
	ID          string `json:"id"`
	GitHash     string `json:"gitHash"`
	Author      string `json:"author"`
	Approver    string `json:"approver"`
	RepoURL     string `json:"repoURL"`
	ArtifactURL string `json:"artifactURL"`
	Created     string `json:"created"`
}

type ReleasePage struct {
	Items     []*Release `json:"items"`
	NextToken *string    `json:"nextToken"`
}
